name: do20_app
description: Start on something

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  go_router: ^13.0.1
  provider: ^6.1.1
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_ui_auth: ^1.12.0
  google_sign_in: ^6.2.1
  firebase_ui_oauth_google: ^1.2.17
  firebase_ui_oauth_apple: ^1.2.17
  intl: ^0.18.1
  easy_localization: ^3.0.3
  firebase_database: ^10.4.4
  firebase_crashlytics: ^3.4.15
  firebase_analytics: ^10.8.6
  wave: ^0.2.2
  shared_preferences: ^2.2.3
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    