// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTQxfH26XmfavSc9hWcz6iWa0VfgkD2P4',
    appId: '1:531537070392:web:f7ea73432a17826ae3d9cd',
    messagingSenderId: '531537070392',
    projectId: 'do20-flutter-4ed7f',
    authDomain: 'do20-flutter-4ed7f.firebaseapp.com',
    storageBucket: 'do20-flutter-4ed7f.appspot.com',
    measurementId: 'G-YZCBEQNRHT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIejY1ffLTgQT5bv-00wehnSh77aBU0MY',
    appId: '1:531537070392:android:cc84ca44a46ad8abe3d9cd',
    messagingSenderId: '531537070392',
    projectId: 'do20-flutter-4ed7f',
    storageBucket: 'do20-flutter-4ed7f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI9TfPQi4CluVS7oRB1p03GCQ4tfshVAc',
    appId: '1:531537070392:ios:a60af7d34f543c80e3d9cd',
    messagingSenderId: '531537070392',
    projectId: 'do20-flutter-4ed7f',
    storageBucket: 'do20-flutter-4ed7f.appspot.com',
    iosBundleId: 'com.example.do20Application1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI9TfPQi4CluVS7oRB1p03GCQ4tfshVAc',
    appId: '1:531537070392:ios:2c2d37a7b58d9455e3d9cd',
    messagingSenderId: '531537070392',
    projectId: 'do20-flutter-4ed7f',
    storageBucket: 'do20-flutter-4ed7f.appspot.com',
    iosBundleId: 'com.example.do20Application1.RunnerTests',
  );
}
